### ISSUE TITLE
Download as PDF: incorrect rendering

### ISSUE THREAD

**Issue by JimJarvis** [yoavram/markx#62]
When I "download as PDF", the latex rendering is frequently incorrect (sometimes correct but ugly, like no blank spaces), but WYSIWYG editor always renders correctly. This makes the PDF export feature mostly unusable. 

**Here's an incorrect case**

WYSIWYG:

![image](https://cloud.githubusercontent.com/assets/3018029/10265342/5097c9f2-69fb-11e5-9cd8-b43b8075515f.png)

Downloaded pdf:

![image](https://cloud.githubusercontent.com/assets/3018029/10265331/e3dd3b62-69fa-11e5-8178-57ae0ce62feb.png)

**Here's a bad-looking (and incorrect) case**

WYSIWYG:

![image](https://cloud.githubusercontent.com/assets/3018029/10265367/b2237e5a-69fb-11e5-9f75-15dabb10de66.png)

Downloaded pdf:

![image](https://cloud.githubusercontent.com/assets/3018029/10265366/a7b4c1c2-69fb-11e5-864d-d668ac0d4028.png)

**Comment by yoavram** [comment]
Which renderer are you using? Pandoc or Docverter (P or D)?

**Comment by JimJarvis** [comment]
Docverter

FYI, the markdown code in the previous screenshot is

```
And define the advantages correspondingly:

- $Adv_{switch} = X_1 - X_0 = \mathcal P[b' \rightarrow 1\ |\ \delta = 1] - \mathcal P[b' \rightarrow 1\ |\ \delta = 0]$
- $Adv_{1} = X_0 - X_2 =\mathcal P[b' \rightarrow 1\ |\ \delta = 0] - \mathcal P[b' \rightarrow 1\ |\ \delta = 2]$
- $Adv_{2} = X_2 - X_1 =\mathcal P[b' \rightarrow 1\ |\ \delta = 2] - \mathcal P[b' \rightarrow 1\ |\ \delta = 1]$
```

**Comment by JimJarvis** [comment]
So I just tried pandoc. The online app "download as pdf" works well, but the local server script doesn't.

**Comment by yoavram** [comment]
Re Docverter - I suggest to open an issue on Docverter repo.
Re local script - what do you mean "doesn't work?" Bad rendering? Error? Nothing at all?

**Comment by JimJarvis** [comment]
By "doesn't work", I mean it renders like Docverter: sometimes correct, sometimes it prints out raw latex code (just like one of the early screenshots I posted).

**Comment by yoavram** [comment]
OK. That could mean that the pandoc version on Docverter and on your machine are different from the one on markx. Try installing the same version as markx: download pandoc from the link in https://github.com/yoavram/markx/blob/master/.vendor_urls

**Comment by JimJarvis** [comment]
Will do. Thanks for your help!

**Comment by yoavram** [comment]
Sure! If you do check it, please update this issue with your conclusions!! Thanks for using markx and for reporting this issue (and others).

**Comment by JimJarvis** [comment]
No problem! Thanks for all your great efforts in Markx. It's an awesome app.

**Comment by cben** [comment]
As for Docverter, there is an existing issue:
https://github.com/Docverter/docverter/issues/12
Basically Docverter’s author doesn’t want to install & run LaTeX.
I’ll ping him about enabling math in the markdown -> HTML [-> PDF] route,
which should be totally doable.

I’ve been eyeing https://github.com/mrded/pandoc-as-a-service/ as a
Docverter alternative for my own need.
I’ve volunteered myself
<https://github.com/mrded/pandoc-as-a-service/issues/4> to add math options
but haven’t touched it yet.
​

**Comment by yoavram** [comment]
Great, let us know how things advance and maybe we can use it for markx, too.
